### ISSUE TITLE
Pull deploymentAddAlert mutation from updateDeployment resolver

### ISSUE THREAD

**Issue by petedejoy** [astronomer/houston-api#100]
In reference to https://github.com/astronomer/astronomer/issues/394#issuecomment-518333398

We need to have a separate mutation for adding an email for alerts to a deployment. Otherwise, an error is thrown if the workspace is on a trial since updating deployment configs is not allowed for trial users.

**Comment by schnie** [comment]
Orbit and Houston PRs merged!
