### ISSUE TITLE
Lose permission on deployments when helm release is purged and re-installed

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/houston-api#111]
**Describe the bug**

When I 'helm delete --purge' the release, then re-deploy with an identical configuration, then my user loses permissions on all airflow deployments.

**To Reproduce**

In a fresh or isolated environment,
```
helm install -f /path/to/config.yaml . --namespace astronomer -n astronomer
```
- log in as the first user
- make an Airflow deployment, wait for it to come up (i chose k8s)
- confirm you can reach airflow dashboard
- save configurations of helm release:
```
helm get astronomer > temp_config.yaml
```
- delete the astronomer release:
```
helm delete --purge astronomer
```
- re-create the release with the same configuration:
```
helm install -f temp_config.yaml . --namespace astronomer -n astronomer
```
- wait for it to come up, then log in
- attempt to go to the existing Airflow deployment
- presented with page "Uh oh! You do not have permission to view that page"

**Expected behavior**
Should still be able to access Airflow after re-deploy

@schnie please re-assign to applicable person. I can take it if you want.

**Comment by sjmiller609** [comment]
note: I am able to go to configure > delete after redeploy

**Comment by sjmiller609** [comment]
note: Astronomer v0.10.0-rc.6

**Comment by sjmiller609** [comment]
note: I used GitHub authentication

**Comment by schnie** [comment]
Good catch, yea I was able to re-create this just now too. @ashb any idea why this would happen? Permission error from the security manager it seems

**Comment by ianstanton** [comment]
Ran into this today when upgrading a customer

**Comment by schnie** [comment]
@ashb is on it in the morning. Should know more soon.

**Comment by schnie** [comment]
NGINX ingress logs during a request to the broken airflow...
```
10.150.0.55 - [10.150.0.55] - - [20/Aug/2019:01:36:35 +0000] "GET /v1/authorization HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.35 Safari/537.36" 1923 0.065 [datarouter-knobby-toucan-houston-houston-http] 10.28.15.230:8871 2 0.065 200 c5f1ff106e086196a8df460e6955d2fa
10.150.0.65 - [10.150.0.65] - - [20/Aug/2019:01:36:35 +0000] "GET / HTTP/2.0" 200 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.35 Safari/537.36" 0 0.069 [datarouter-uninhabited-exposure-8039-uninhabited-exposure-8039-webserver-airflow-ui] 35.230.189.177:443 0 0.068 200 55ac42db251b0af618c236b4c292d948
10.150.0.65 - [10.150.0.65] - - [20/Aug/2019:01:36:35 +0000] "GET / HTTP/2.0" 403 571 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.35 Safari/537.36" 21 0.076 [upstream-default-backend] 10.28.26.150:8080 : 10.28.16.89:8080 0 : 1046 0.005 : 0.003 403 : 403 55ac42db251b0af618c236b4c292d948
```

**Comment by schnie** [comment]
Hmm, getting closer I think. Looks like there's an issue mounting the JWT signing certificate into the airflow pods. Looking at the broken deployment, there's a webserver pod crash looping with...
```
kubectl logs uninhabited-exposure-8039-webserver-9cd597cd9-cn46w 
Waiting for host: uninhabited-exposure-8039-pgbouncer 6543
Initializing airflow database...
[2019-08-20 01:46:16,620] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=20
[2019-08-20 01:46:18,758] {__init__.py:51} INFO - Using executor KubernetesExecutor
DB: postgresql://uninhabited_exposure_8039_airflow:***@uninhabited-exposure-8039-pgbouncer:6543/uninhabited-exposure-8039-metadata
[2019-08-20 01:46:20,098] {db.py:369} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Done.
[2019-08-20 01:46:23,324] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=25
[2019-08-20 01:46:25,290] {__init__.py:51} INFO - Using executor KubernetesExecutor
Traceback (most recent call last):
  File "/usr/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/airflow/bin/cli.py", line 1472, in sync_perm
    appbuilder = cached_appbuilder()
  File "/usr/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 237, in cached_appbuilder
    cached_app(config=config, testing=testing)
  File "/usr/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 230, in cached_app
    app, _ = create_app(config, session, testing)
  File "/usr/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 103, in create_app
    base_template='appbuilder/baselayout.html')
  File "/usr/lib/python3.7/site-packages/flask_appbuilder/base.py", line 138, in __init__
    self.init_app(app, session)
  File "/usr/lib/python3.7/site-packages/flask_appbuilder/base.py", line 160, in init_app
    self.sm = self.security_manager_class(self)
  File "/usr/lib/python3.7/site-packages/astronomer/flask_appbuilder/security.py", line 255, in __init__
    with open(conf.get('astronomer', 'jwt_signing_cert'), 'rb') as fh:
IsADirectoryError: [Errno 21] Is a directory: '/etc/airflow/tls/tls.crt'
```
Checking the values of the broken deployment:
```
$ helm get values uninhabited-exposure-8039
...
...
webserver:
  jwtSigningCertificateSecretName: knobby-toucan-houston-jwt-certificate
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 10Gi
      memory: 1920Mi
    requests:
      cpu: 500m
      ephemeral-storage: 5Gi
      memory: 1920Mi
...
...
```

And then describing the jwt secret...
```
kc describe secret knobby-toucan-houston-jwt-certificate
Name:         knobby-toucan-houston-jwt-certificate
Namespace:    datarouter-uninhabited-exposure-8039
Labels:       chart=airflow
              heritage=Tiller
              release=uninhabited-exposure-8039
Annotations:  replicator.v1.mittwald.de/replicate-from: datarouter/knobby-toucan-houston-jwt-certificate
              replicator.v1.mittwald.de/replicated-at: 2019-08-19T17:09:07Z
              replicator.v1.mittwald.de/replicated-from-version: 145753854

Type:  Opaque

Data
====
```

So it looks like the JWT signing certificate is empty with no keys.

**Comment by schnie** [comment]
Generated secret in the platform namespace for the datarouter release seems fine...
```
$ kubectl describe secret knobby-toucan-houston-jwt-certificate                                     
Name:         knobby-toucan-houston-jwt-certificate
Namespace:    datarouter
Labels:       chart=astronomer-0.10.0-rc.8
              component=houston
              heritage=Tiller
              release=knobby-toucan
              tier=astronomer
Annotations:  helm.sh/hook: pre-install
              helm.sh/hook-delete-policy: before-hook-creation
              helm.sh/hook-weight: 0
              replicator.v1.mittwald.de/replication-allowed: true
              replicator.v1.mittwald.de/replication-allowed-namespaces: datarouter-*

Type:  Opaque

Data
====
tls.crt:  1204 bytes
tls.key:  1675 bytes
```

**Comment by schnie** [comment]
Ok, just upgraded the platform again and tested against a separate deployment that I did _not_ attempt a code push to. This time, the webserver is still happily running and I can `kubectl exec` into the webserver and `cat /etc/airflow/tls/tls.crt`, which makes sense. The previous platform installations certificate is still in memory and being used to decode the JWTs and clearly failing. 

In this screenshot, the left side is the `cat` output from inside the webserver pod, and the right side is the decoded value of the new platform JWT secret. This shows that they are two different values. 

![2019-08-19_000](https://user-images.githubusercontent.com/1036482/63312121-7300e200-c2ce-11e9-8c5e-c672f562c229.png)

So one way or another, we need to figure out a way to ensure that the certificate we use to sign JWTs in houston stays synced with the ones mounted inside the running airflow pods. Maybe we start piggybacking off `astronomer-tls` for this? Or possibly some different helm tricks on this secret... :thinking:

**Comment by schnie** [comment]
I can't figure out a way to have helm generate a secret once, leave it around after a delete and re-use the old value if followed up by another install. It's essentially the same issue described here - https://github.com/helm/helm/issues/3053.

We _could_ piggyback off `astronomer-tls`, but we'd have to add some install steps to run `kubectl annotate` a few times to get these annotations onto `astronomer-tls`: https://github.com/astronomer/helm.astronomer.io/blob/master/charts/astronomer/templates/houston/houston-jwt-certificate-secret.yaml#L21-L24. This isn't as big a deal, now that we use terraform for the inital components mostly, but will add steps to anyone not using terraform.

I also don't think that really gets us completely out of the woods since that certificate will get reloaded at some point in the future as well. It's like we need a way to signal to all the airflow webservers to reload the certificate, or something...

@ashb @ryw @sjmiller609 @vparekh94 @ianstanton any thoughts here?

**Comment by schnie** [comment]
Rethinking this now... maybe we shouldn't piggyback off `astronomer-tls` and instead add a step to the install process (automated if using terraform), to create the separate secret [(this one)](https://github.com/astronomer/helm.astronomer.io/blob/master/charts/astronomer/templates/houston/houston-jwt-certificate-secret.yaml) with the proper annotations and everything and just leave it alone, never updating it, avoiding this issue altogether.

Might not be the super long-term fix since we'll probably want to have the ability to rotate certificates, but could get us going now.

**Comment by schnie** [comment]
Also, I'm not sure why the airflow deployment secret gets blanked out instead of updated with the latest value...

I was able to repair a busted deployment by:
1) `kubectl delete secret knobby-toucan-houston-jwt-certificate` from airflow namespace
2) `kubectl apply -f` something like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: knobby-toucan-houston-jwt-certificate
  annotations:
    replicator.v1.mittwald.de/replicate-from: datarouter/knobby-toucan-houston-jwt-certificate
data: {}
```
This creates a blank secret that the replicator will replicate into automatically. Check it after a second.
3) Reboot webserver pod to mount the correct cert.

**Comment by ashb** [comment]
Could we use something like https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change to automatically restart airflow webserver when this secret changes? Or is the problem that kube-replicator is messing up and loosing track?

**Comment by ashb** [comment]
Looking like it's a bug in kube-replicator:

The secret in the airflow NS has this annotation:

```yaml
    replicator.v1.mittwald.de/replicated-from-version: "145933224"
```

And that is the resourceVersion of the secret in the platform namespace. But the data isn't replicated.

**Comment by schnie** [comment]
Ok, I think we're done here, for now. Here's what we did:
1) Swap out `kube-replicator` in favor of `kubed`, this got us around the replication bugs where secrets got blanked out.
2) Divy up the key/cert for houston JWTs into two secrets allowing us to drop usage of `subPath` with our volume mounts. `subPath` and automatically updating secret values inside pods are not compatible. This lets us avoid it and re-gain the auto updating secrets.
3) Update our airflow security manager to refresh the cert from disk if needed when requests come in.
