### ISSUE TITLE
Feature Suggestion: Provide endpoint for Log Streaming

### ISSUE THREAD

**Issue by benjamingregory** [astronomer/houston-api#49]
Requested by customer --

As a user of Astronomer, I want the ability to subscribe to an endpoint to stream scheduler, webserver, and worker logs to then put into an S3 bucket or other bulk location for post-processing.

**Comment by schnie** [comment]
@benjamingregory we do have a log query and subscription in our GraphQL API now, which powers the UI and CLI, but may need an upgrade to support larger time frames for this use-case.

Just for a little more context, do you know what kind of processing they want to do on airflow logs, and are the scheduler/webserver important for this or just the task logs?

**Comment by benjamingregory** [comment]
@schnie I believe it was for every log available (e.g. scheduler, webserver, workers, tasks) -- anything thats exposed in the Astro or Airflow UI.

**Comment by schnie** [comment]
@benjamingregory any idea on what the use-case is? Doesn't seem like webserver/scheduler logs would be all that interesting and if the workers are, what are they looking to do?

**Comment by ryw** [comment]
this is done :) https://github.com/astronomer/astro-cli/blob/master/cmd/logs.go
