### ISSUE TITLE
Fix redirect_uri in Okta integration

### ISSUE THREAD

**Issue by petedejoy** [astronomer/houston-api#78]
As of now, we set the auth0 baseDomain to be `auth0.astronomer.io` by default. This causes the universal oauth `redirect_uri` to be `https://redirect.astronomer.io`, even though that should only be true if the user is leveraging the Auth0 integration.

The `redirect_uri` for the Okta integration should be the customer's default URL. I'm going to make a new `useGlobalRedirect` config that causes the `redirect_uri` to be set to the correct URL if the config is false.

**Comment by schnie** [comment]
@petedejoy @ashb this is fixed with openid connect right?

**Comment by petedejoy** [comment]
So part of this problem (ie. the fact that the okta redirect_uri would default to redirect.astronomer.io if a baseDomain for auth0 was not defined) is fixed. However, now that I'm thinking about it, we had to whitelist https://redirect.astronomer.io in our okta app settings given the new oidc setup. I'm not sure if this will be possible for WH. This was one of the things I asked of them early on: 

![image](https://user-images.githubusercontent.com/32076749/61241863-6bb84880-a712-11e9-92e1-ccadd609d42d.png)

@ashb - wondering what your thoughts are here. Are we able to configure okta if they're using us completely offline and don't want to whitelist that domain?
