### ISSUE TITLE
Support sending invite emails

### ISSUE THREAD

**Issue by schnie** [astronomer/houston-api#8]
Implement the ability to invite users to the system, as Houston 1 does.

**Comment by schnie** [comment]
@ashb still need to dig in more, but there might be a bug with the invite system. 

@petedejoy and I both tried and got a similar situation. After inviting someone, an the new user follows the email link, and signs up, it appears that the user does not end up added to the workspace they were invited to. Maybe a missing roleBinding?

**Comment by schnie** [comment]
Looks like if you go and add the user a second time, after they've actually created an account, they get added to the workspace successfully, so it just seems like the invite flow is the issue.

**Comment by schnie** [comment]
Also looks like if you get invited, follow the email link and sign up, it'll send you a link to confirm your email. I'm thinking we should suppress the confirm email if they were invited - the invite email should count as the confirmation.

**Comment by ashb** [comment]
Okay, will take a look.

> the invite email should count as the confirmation.

Yes, sounds sensible
