### ISSUE TITLE
Support sending and re-sending email verification

### ISSUE THREAD

**Issue by schnie** [astronomer/houston-api#9]
We need to add the sending of a verification email when users signup, as well as the ability to re-send the email. The signup mutation already exists, it just needs to be modified to send an email. The re-send mutation needs to be added.

**Comment by ashb** [comment]
Do we let people sign in before the email is validated?

In my (limited) local testing of Orbit I haven't seen where the re-send email is done. Are both of these related to a setting I've not got on, or is it expected that the `createToken` mutation will return an error on attempted sign in for an un-verified user?
